### ISSUE TITLE
RSS Feed error on Dashboard and on Kiosk plugin for news and gallery

### ISSUE THREAD

**Issue by chasethenag420** [gios-asu/gios-vagrant#22] opened 2015-08-26 22:54 UTC
A strange error which related to SimplePie feed pull using  for both Dashboard news feed and the Kiosk rss feed in general for all which uses SimplePie to fetch rss feed. For the same version of wordpress its working my local system but not on vagrant machine tried with different version of wordpress but problem still persists. 
[Issue reported on Core Trac](https://core.trac.wordpress.org/ticket/29204)
[Dashboard plugin issue](https://github.com/wp-e-commerce/WP-e-Commerce/issues/1776)

![screenshot from 2015-08-26 15 45 55](https://cloud.githubusercontent.com/assets/10416054/9508406/f1dada58-4c09-11e5-856c-bfb60d1bc956.png)

**Comment by rraub** [comment] 2015-09-01 00:50
I think you posted this issue in the wrong github project.

**Comment by rraub** [comment] 2015-09-01 20:42
Per our conversation, with the php error reporting setting [in the install_php script](https://github.com/gios-asu/gios-vagrant/blob/master/image_scripts/install_php.sh#L43) this is the intended behavior, if the error is not displayed on your local workstation then its an issue with that setup. I think we can close this issue, unless @chasethenag420 you something else thats wrong.

**Closed as completed** 2015-09-08 19:05 UTC
Labels: bug, help wanted, question
